"""
Django settings for niftybot project.

Generated by 'django-admin startproject' using Django 5.0+.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
# Change this to a long random string in production!
# Generate one with: python -c "import secrets; print(secrets.token_urlsafe(50))"
SECRET_KEY = 'django-insecure-CHANGE-THIS-TO-A-VERY-LONG-RANDOM-STRING-IN-PRODUCTION-2026'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']  # ← CHANGE IN PRODUCTION: add your real domain


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Add this line ↓
    'django.contrib.humanize',          # ← REQUIRED for |intcomma, |naturalday, etc.

    # Your app
    'trading',
    
    # Celery stuff
    'django_celery_beat',
    'django_celery_results',

    # Redis cache (if you added it earlier)
    'django_redis',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'niftybot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'niftybot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'Atchut1234',
        'HOST': 'rohitdb.ckl6umkmkrui.us-east-1.rds.amazonaws.com',
        'PORT': '5432',
    }
}
#pip install psycopg2-binary


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
import os

STATIC_URL = '/static/'

# Development: local static files folder
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Production: where collectstatic will collect files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Production: collectstatic destination

# Media files (user uploads - if you add any later)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Login / Auth settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'


# ───────────────────────────────────────────────
# CELERY CONFIGURATION (critical for trading bot)
# ───────────────────────────────────────────────

CELERY_BROKER_URL = 'redis://localhost:6379/0'           # Redis as broker
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'       # Redis for results

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Very important for long-running trading bots
CELERY_TASK_TIME_LIMIT = None           # No hard timeout
CELERY_TASK_SOFT_TIME_LIMIT = None      # No soft timeout
CELERY_TASK_ACKS_LATE = True            # Only ack after task completes
CELERY_WORKER_PREFETCH_MULTIPLIER = 1   # Don't prefetch multiple tasks
CELERY_TASK_TRACK_STARTED = True        # Track when tasks start

# Celery Beat (periodic tasks) - if using scheduler
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'


# ───────────────────────────────────────────────
# REDIS CACHE (highly recommended for Celery + real-time dashboard)
# ───────────────────────────────────────────────

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",  # Different DB than Celery (0)
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100},
        }
    }
}

# Use Redis for session storage (optional but good for scaling)
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"


# ───────────────────────────────────────────────
# EMAIL CONFIGURATION (for alerts, notifications)
# ───────────────────────────────────────────────

# Development: print emails to console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Production example (uncomment and configure):
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'


# ───────────────────────────────────────────────
# LOGGING (improved visibility for trading bot)
# ───────────────────────────────────────────────

# Ensure logs directory exists (fixes the ValueError)
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)  # Auto-create folder

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'niftybot.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'trading': {  # Your app logger
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}


# ───────────────────────────────────────────────
# SECURITY SETTINGS (uncomment / configure in production)
# ───────────────────────────────────────────────

# SECURE_SSL_REDIRECT = True                    # Force HTTPS
# SESSION_COOKIE_SECURE = True                  # Cookies only over HTTPS
# CSRF_COOKIE_SECURE = True                     # CSRF only over HTTPS
# SECURE_HSTS_SECONDS = 31536000                # 1 year HSTS
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# SECURE_BROWSER_XSS_FILTER = True
# X_FRAME_OPTIONS = 'DENY'


# ───────────────────────────────────────────────
# STATIC FILES (CSS, JS, Images)
# ───────────────────────────────────────────────
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
          # Development: local static files
STATIC_ROOT = BASE_DIR / 'staticfiles'            # Production: collectstatic destination