# Generated by Django 5.2.11 on 2026-02-05 07:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BotStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_running", models.BooleanField(default=False)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_started", models.DateTimeField(blank=True, null=True)),
                ("last_stopped", models.DateTimeField(blank=True, null=True)),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                (
                    "current_unrealized_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "current_margin",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "daily_profit_target",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Today's Profit Target (₹)",
                    ),
                ),
                (
                    "daily_stop_loss",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Today's Stop Loss (₹)",
                    ),
                ),
                (
                    "max_lots_hard_cap",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum lots the bot is allowed to trade (1 = safest)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "entry_attempted_date",
                    models.DateField(
                        blank=True,
                        help_text="Date on which an entry was last attempted (prevents duplicate entries same day)",
                        null=True,
                    ),
                ),
                (
                    "last_successful_entry",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last successful trade entry",
                        null=True,
                    ),
                ),
                ("state_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot Status",
                "verbose_name_plural": "Bot Statuses",
            },
        ),
        migrations.CreateModel(
            name="Broker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("broker_name", models.CharField(default="ZERODHA", max_length=50)),
                ("api_key", models.CharField(max_length=255)),
                ("secret_key", models.CharField(max_length=255)),
                (
                    "totp",
                    models.CharField(
                        blank=True,
                        help_text="TOTP secret for 2FA",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "zerodha_user_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Zerodha User ID",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="Only needed for initial login flow",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "request_token",
                    models.CharField(
                        blank=True,
                        help_text="Paste the request_token from manual Zerodha login redirect URL",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated access token (saved after successful login)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "token_generated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when access_token was last generated/renewed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brokers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Broker Connection",
                "verbose_name_plural": "Broker Connections",
                "ordering": ["-updated_at"],
                "unique_together": {("user", "broker_name")},
            },
        ),
        migrations.CreateModel(
            name="DailyPnL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "algorithm_name",
                    models.CharField(default="Hedged Short Strangle", max_length=100),
                ),
                ("date", models.DateField()),
                ("pnl", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_trades", models.PositiveIntegerField(default=0)),
                ("win_trades", models.PositiveIntegerField(default=0)),
                ("loss_trades", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_pnl",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily P&L",
                "verbose_name_plural": "Daily P&L Records",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Entry",
                "verbose_name_plural": "Log Entries",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="trading_log_user_id_4eb86c_idx",
                    ),
                    models.Index(fields=["level"], name="trading_log_level_3dd346_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "algorithm_name",
                    models.CharField(default="Hedged Short Strangle", max_length=100),
                ),
                ("trade_id", models.CharField(max_length=100, unique=True)),
                ("symbol", models.CharField(max_length=50)),
                ("quantity", models.IntegerField()),
                ("entry_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("entry_time", models.DateTimeField()),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                (
                    "pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("EXECUTED", "Executed"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("broker", models.CharField(default="ZERODHA", max_length=50)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-entry_time"],
                "indexes": [
                    models.Index(
                        fields=["user", "entry_time"],
                        name="trading_tra_user_id_490c50_idx",
                    ),
                    models.Index(
                        fields=["trade_id"], name="trading_tra_trade_i_b44db8_idx"
                    ),
                    models.Index(
                        fields=["status"], name="trading_tra_status_252e0c_idx"
                    ),
                ],
            },
        ),
    ]
